language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - travis_retry composer self-update
  - travis_retry composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - sh ./maketests.sh
  - php vendor/bin/codecept run
